# Generated by Django 5.2.6 on 2025-09-18 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_url", models.URLField(unique=True, verbose_name="Site URL")),
                ("rss_url", models.URLField(max_length=255, verbose_name="RSS url")),
                ("title", models.CharField()),
                ("subtitle", models.CharField()),
                ("author", models.CharField()),
                ("etag", models.CharField()),
                ("modified", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField()),
                ("title", models.CharField()),
                ("published", models.DateTimeField()),
                ("author", models.CharField()),
                ("content", models.TextField()),
                ("summary", models.TextField()),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rss_reader.feed",
                    ),
                ),
            ],
        ),
    ]
