# Generated by Django 5.2.6 on 2025-10-07 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_url", models.URLField(max_length=255, verbose_name="Site URL")),
                ("rss_url", models.URLField(unique=True, verbose_name="RSS url")),
                ("title", models.CharField()),
                ("subtitle", models.CharField()),
                ("author", models.CharField()),
                ("etag", models.CharField()),
                ("modified", models.DateTimeField(null=True)),
                ("entry_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Feeds",
                "db_table": "rss_reader_feeds",
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField()),
                ("title", models.CharField()),
                ("published", models.DateTimeField(db_index=True)),
                ("author", models.CharField()),
                ("content", models.TextField()),
                ("summary", models.TextField()),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rss_reader.feed",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entries",
                "db_table": "rss_reader_entries",
                "ordering": ["-published"],
                "unique_together": {("feed", "link")},
            },
        ),
        migrations.CreateModel(
            name="UserEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rss_reader.entry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User entries",
                "db_table": "rss_reader_user_entries",
                "indexes": [
                    models.Index(
                        condition=models.Q(("read", True)),
                        fields=["user", "read"],
                        name="user_entry_partial_read",
                    )
                ],
                "unique_together": {("user", "entry")},
            },
        ),
        migrations.CreateModel(
            name="UserFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stale", models.BooleanField(default=True)),
                ("read_count", models.PositiveIntegerField(default=0)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rss_reader.feed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User feeds",
                "db_table": "rss_reader_user_feeds",
                "unique_together": {("user", "feed")},
            },
        ),
    ]
