# Generated by Django 5.2.7 on 2025-10-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss_reader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="feed_type",
            field=models.CharField(
                default="rss", max_length=10, verbose_name="Feed type"
            ),
        ),
    ]
