# Generated by Django 5.2.6 on 2025-09-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss_reader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeed",
            name="stale",
            field=models.BooleanField(default=False),
        ),
    ]
