# Generated by Django 5.2.7 on 2025-10-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss_reader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True)),
                ("headers", models.TextField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Request history",
                "db_table": "rss_reader_request_history",
            },
        ),
    ]
