# Generated by Django 5.2.6 on 2025-09-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss_reader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="published",
            field=models.DateTimeField(null=True),
        ),
    ]
