# Generated by Django 5.2.6 on 2025-09-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss_reader", "0002_userfeed_stale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeed",
            name="stale",
            field=models.BooleanField(default=True),
        ),
    ]
