# Generated by Django 5.2.7 on 2025-10-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss_reader", "0002_feed_feed_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
