# Generated by Django 5.2.7 on 2025-10-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rss_reader", "0002_requesthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesthistory",
            name="status",
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
