# Generated by Django 5.2.7 on 2025-10-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss_reader", "0003_requesthistory_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="image",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="favicons/",
                verbose_name="img",
            ),
        ),
    ]
