# Generated by Django 5.2.8 on 2025-11-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rss_reader", "0004_feed_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="last_exception",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="last_response_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
