# Generated by Django 5.2.8 on 2025-11-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rss_reader", "0005_feed_last_exception_feed_last_response_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="disabled_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="update_after",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="update_interval",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="feed",
            name="updates_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
