# Generated by Django 5.2.8 on 2025-11-14 18:09

from django.db import migrations
from django.db.models.aggregates import Max
from django.utils import timezone


SECONDS_IN_HOUR = 3600
HOURS_IN_YEAR = 24 * 365
HOURS_IN_MONTH = 24 * 30


def fill_update_interval_and_update_after(apps, schema_editor):
    Feed = apps.get_model("rss_reader", "Feed")
    Entry = apps.get_model("rss_reader", "Entry")
    current_time = timezone.now()
    latest_dates = (
        Entry.objects.values_list("feed_id")
        .annotate(lastest_published=Max("published"))
        .values_list("feed_id", "lastest_published")
    )
    latest_dates = dict(latest_dates)
    feeds = Feed.objects.all()
    for feed in feeds:
        lastest_published = latest_dates.get(feed.id)
        if lastest_published is not None:
            average_time_delta = (
                current_time - lastest_published
            ).total_seconds() / SECONDS_IN_HOUR
            average_time_delta = int(average_time_delta)
            if average_time_delta:
                average_time_delta = int(average_time_delta)
                if average_time_delta > HOURS_IN_YEAR:
                    feed.updates_enabled = False
                    feed.update_interval = HOURS_IN_MONTH
                    feed.disabled_reason = "Last updated more than a year ago"
                else:
                    feed.update_interval = average_time_delta
                feed.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("rss_reader", "0006_feed_disabled_reason_feed_update_after_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_update_interval_and_update_after, backwards),
    ]
