# Generated by Django 6.0 on 2025-12-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rss_reader", "0007_auto_20251114_2109"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeed",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
