# Generated by Django 6.0 on 2025-12-21 16:57

from django.db import migrations
from django.db.models import F


def fill_update_interval_and_update_after(apps, schema_editor):
    UserFeed = apps.get_model("rss_reader", "UserFeed")
    UserFeed.objects.update(sort_order=F("id"))


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("rss_reader", "0008_userfeed_sort_order"),
    ]

    operations = [
        migrations.RunPython(fill_update_interval_and_update_after, backwards),
    ]
