name: rss_reader
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=local,src=${UV_CACHE_DIR}
    user: "${UID}:${GID}"
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - ./data/:/data/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - postgres:postgres
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - db_network
      - rabbitmq_network
      - redis_network

  postgres:
    image: postgres:18
    container_name: postgres
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - '127.0.0.1:5433:5432'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 2s
      retries: 5
    networks:
      - db_network
    secrets:
     - db_password

  rabbitmq:
    image: rabbitmq:4
    container_name: rabbitmq
    ports:
      - '127.0.0.1:5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - rabbitmq_network

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m celery -A django_rss_reader worker --loglevel=INFO
    user: "${UID}:${GID}"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    links:
      - postgres:postgres
    networks:
      - db_network
      - rabbitmq_network
      - redis_network

  celery_beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m celery -A django_rss_reader beat
    depends_on:
      rabbitmq:
        condition: service_started
    networks:
      - rabbitmq_network

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - redis_network
    volumes:
      - redis_data:/data

volumes:
  rabbitmq_data:
  redis_data:

networks:
  db_network:
  rabbitmq_network:
  redis_network:

secrets:
   db_password:
     file: db_password.txt
