CACHE_FAVICON_PREFIX = "favicon:"
HOURS_IN_DAY = 24
HOURS_IN_THREE_DAYS = HOURS_IN_DAY * 3
HOURS_IN_WEEK = HOURS_IN_DAY * 7
HOURS_IN_MONTH = HOURS_IN_DAY * 30
HOURS_IN_YEAR = HOURS_IN_DAY * 365

WS_TASKS_REFRESHED_GROUP_NAME = "tasks_refreshed"
ENTRIES_BATCH_SIZE = 25
